name: Lints

on: [ push, pull_request ]

jobs:
  lints:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn
    - run: yarn lint